apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\rtinsley\Desktop\todo-spike\kompose.exe convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  ports:
  - name: "1401"
    port: 1401
    targetPort: 1433
  selector:
    io.kompose.service: database
status:
  loadBalancer: {}
