apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\rtinsley\Desktop\todo-spike\kompose.exe convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: Passw0rd
        image: microsoft/mssql-server-linux:2017-latest
        name: database
        ports:
        - containerPort: 1433
        resources: {}
      restartPolicy: Always
status: {}
