version: '3'

services:
  web:
    image: todo
    build:
      context: .
      dockerfile: Todo/Dockerfile
    ports:
      - 10000:80
    depends_on:
      - database

  database:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - 1401:1433
    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: Y