version: '3'

services:
  web:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - keys:/var/keys

  database:
    restart: always

  proxy:
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  keys: