version: '3'

services:
  web:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  
  database:
    restart: always

  proxy:
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - web
    depends_on:
      - database
